branches:
  - master
  - develop

language: php

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

env:
  - DB=mysql

before_script:
  - mysql -e 'CREATE DATABASE `biz-framework-test` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci'
  - composer install
cache:
  directories:
    - $HOME/.composer/cache
